### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Graeme-Smith** [sguizard/DensityMap#2]
Hi.  I really like your tool, just one small issue with the usage example returned when -help is used.

USAGE: DensityMap.pl -gff chromosome.gff3 -ty 'match=all' -o Chromosome

Shouldn't the -gff be -i for input?

Cheers

**Comment by sguizard** [comment]
Hi ! 

Thank you for your review ! 
You are right about the USAGE, -gff came from the very first version of the program. 
I replaced it with the correct -i !

Cheers
